### ISSUE TITLE
Crash when trying .resolve with arguments

### ISSUE THREAD

**Issue by siggb** [Swinject/Swinject#161]
Hello!
I've just found that passing argument(-s) to `resolve` function doesn't work in version `2.0.0-beta.2`.
My code below:

    container.register(CharactersListViewOutput.self) { (r, view: CharactersListViewInput) in
        let presenter = CharactersListPresenter()
        presenter.view = view
        return presenter
    }
    container.register(CharactersListViewInput.self) { r in
        let view = CharactersListViewController()
        let presenter = r.resolve(CharactersListViewOutput.self, argument: view)! //must be not nill
        view.output = presenter
        return view
    }

Crashing here:
`let presenter = r.resolve(CharactersListViewOutput.self, argument: view)`

Build log:
```
expression produced error: error: /var/folders/vm/mxkwkr0j6ys_fw6ngk7641440000gn/T/./lldb/8675/expr4.swift:1:65: error: use of undeclared type 'CharactersListViewOutput'
Swift._DebuggerSupport.stringForPrintObject(Swift.UnsafePointer<CharactersListViewOutput>(bitPattern: 0x10ff25200)!.pointee)
```

**Comment by siggb** [comment]
Resolved problem by using `.initCompleted` construction after Parent-Child `register` definitions. 
It is looks like the example from [this comment](https://github.com/Swinject/Swinject/issues/51#issuecomment-179728784) has Circular Dependency problem. So, I just used solution from the [Playground example](https://github.com/Swinject/Swinject/blob/master/Sample-iOS.playground/Contents.swift#L170).
